userdb:
  image: mysql
  hostname: userdb
  ports:
   - "3306:3306"  
  environment:
    - MYSQL_ROOT_PASSWORD=rootpassword
    - MYSQL_DATABASE=userdb
    - MYSQL_USER=userdb
    - MYSQL_PASSWORD=userdb-password

rabbitmq:
  image: rabbitmq:3-management
  hostname: rabbitmq
  ports:
    - "15672:15672"
    - "5672:5672"

cassandra:
  image: openzipkin/zipkin-cassandra:1.25.0
  ports:
    - 9042:9042
    
collector:
  image: openzipkin/zipkin-collector:1.25.0
  environment:
    - TRANSPORT_TYPE=scribe
    - STORAGE_TYPE=cassandra
  expose:
    - 9410
  ports:
    - 9410:9410
    - 9900:9900
  links:
    - cassandra:storage
    
query:
  image: openzipkin/zipkin-query:1.25.0
  environment:
    - TRANSPORT_TYPE=http
    - STORAGE_TYPE=cassandra
  expose:
    - 9411
  ports:
    - 9411:9411
    - 9901:9901
  links:
    - cassandra:storage
web:
  image: openzipkin/zipkin-web:1.25.0
  environment:
    - TRANSPORT_TYPE=http
  ports:
    - 8080:8080
    - 9990:9990
  links:
    - query